<a href="https://colab.research.google.com/github/Darshan2104/CE_135_Darshan_Tank_ML/blob/main/Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Perform all data preprocessing tasks and feature selection on “Exercise-CarData.csv”**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
data = pd.read_csv('/content/drive/MyDrive/L2/Datasets/Exercise-CarData.csv')
data

Unnamed: 0  Price   Age     KM  ... Automatic    CC  Doors  Weight
0              0  13500  23.0  46986  ...         0  2000  three    1165
1              1  13750  23.0  72937  ...         0  2000      3    1165
2              2  13950  24.0  41711  ...         0  2000      3    1165
3              3  14950  26.0  48000  ...         0  2000      3    1165
4              4  13750  30.0  38500  ...         0  2000      3    1170
...          ...    ...   ...    ...  ...       ...   ...    ...     ...
1431        1431   7500   NaN  20544  ...         0  1300      3    1025
1432        1432  10845  72.0     ??  ...         0  1300      3    1015
1433        1433   8500   NaN  17016  ...         0  1300      3    1015
1434        1434   7250  70.0     ??  ...         0  1300      3    1015
1435        1435   6950  76.0      1  ...         0  1600      5    1114

[1436 rows x 11 columns]

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  1436 non-null   int64  
 1   Price       1436 non-null   int64  
 2   Age         1336 non-null   float64
 3   KM          1436 non-null   object 
 4   FuelType    1336 non-null   object 
 5   HP          1436 non-null   object 
 6   MetColor    1286 non-null   float64
 7   Automatic   1436 non-null   int64  
 8   CC          1436 non-null   int64  
 9   Doors       1436 non-null   object 
 10  Weight      1436 non-null   int64  
dtypes: float64(2), int64(5), object(4)
memory usage: 123.5+ KB


In [42]:
data.describe()

Unnamed: 0         Price  ...           CC      Weight
count  1436.000000   1436.000000  ...  1436.000000  1436.00000
mean    717.500000  10730.824513  ...  1566.827994  1072.45961
std     414.681806   3626.964585  ...   187.182436    52.64112
min       0.000000   4350.000000  ...  1300.000000  1000.00000
25%     358.750000   8450.000000  ...  1400.000000  1040.00000
50%     717.500000   9900.000000  ...  1600.000000  1070.00000
75%    1076.250000  11950.000000  ...  1600.000000  1085.00000
max    1435.000000  32500.000000  ...  2000.000000  1615.00000

[8 rows x 7 columns]


## 1. Handling the missing value



In [32]:
from sklearn.impute import SimpleImputer

X = data.iloc[:, :-1].values 
Y = data.iloc[:, -1].values 

# Dope such a rows with all value=nan
data.dropna(how='all',inplace=True) 

# Datatype :floats
imputer = SimpleImputer(missing_values=np.nan,strategy='median')
X[:,[2,6]] = imputer.fit_transform(X[:,[2,6]]) #Specifically for 2nd and 6th column  
 
# Specifically for datatype: objects
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
X[:,[4,9]] = imputer.fit_transform(X[:,[4,9]])


## 2. Data Transformation

In [40]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, Normalizer

**a. Scaling (Min-Max Normalization)**


In [34]:
X_new = X[:,[1,2,6,7,8]] #column with datatype- int or float

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X_new)
X_scaled

array([[0.3250444 , 0.27848101, 1.        , 0.        , 1.        ],
       [0.3339254 , 0.27848101, 1.        , 0.        , 1.        ],
       [0.3410302 , 0.29113924, 1.        , 0.        , 1.        ],
       ...,
       [0.14742451, 0.74683544, 0.        , 0.        , 0.        ],
       [0.10301954, 0.87341772, 1.        , 0.        , 0.        ],
       [0.09236234, 0.94936709, 0.        , 0.        , 0.42857143]])

**b. Mean - Normalization**


In [41]:
scaler = Normalizer()
X_scaled = scaler.fit_transform(X_new)
X_scaled

array([[9.89202055e-01, 1.68530720e-03, 7.32742263e-05, 0.00000000e+00,
        1.46548453e-01],
       [9.89585081e-01, 1.65530595e-03, 7.19698241e-05, 0.00000000e+00,
        1.43939648e-01],
       [9.89876972e-01, 1.70301415e-03, 7.09589227e-05, 0.00000000e+00,
        1.41917845e-01],
       ...,
       [9.88481693e-01, 6.97751783e-03, 0.00000000e+00, 0.00000000e+00,
        1.51179553e-01],
       [9.84257002e-01, 9.50317106e-03, 1.35759587e-04, 0.00000000e+00,
        1.76487463e-01],
       [9.74453893e-01, 1.06558987e-02, 0.00000000e+00, 0.00000000e+00,
        2.24334709e-01]])

**c. Standardization (Z score)**

In [36]:
scaler = StandardScaler()
X_scaled =scaler.fit_transform(X_new)
X_scaled

array([[ 0.76376268, -1.83615212,  0.64078783, -0.24289308,  2.31497633],
       [ 0.83271485, -1.83615212,  0.64078783, -0.24289308,  2.31497633],
       [ 0.88787659, -1.78046649,  0.64078783, -0.24289308,  2.31497633],
       ...,
       [-0.6152808 ,  0.22421608, -1.56057896, -0.24289308, -1.42599356],
       [-0.96004167,  0.78107235,  0.64078783, -0.24289308, -1.42599356],
       [-1.04278428,  1.11518612, -1.56057896, -0.24289308,  0.17727925]])

## 3. Handling Categorical Data

In [43]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

**a. Lable Encoding**

In [48]:
le = LabelEncoder()
X[ : ,4] = le.fit_transform(X[ : ,4])
X[ : ,9] = le.fit_transform(X[ : ,9])


**b. One Hot Encoding**

In [64]:
# dummy = pd.get_dummies(data['Doors'])
# data = data.drop(['Doors',],axis=1)
# data = pd.concat([dummy,data],axis=1)
# dummy = pd.get_dummies(data['FuelType'])
# data = data.drop(['FuelType',],axis=1)
# data = pd.concat([dummy,data],axis=1)

# print("Final\n",data.head())